apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: resortslite-ingress
  namespace: resortslite
  labels:
    app: resortslite
  annotations:
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/ingress.allow-http: "true"
spec:
  rules:
    - host: resortslite.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: resortslite-service
                port:
                  number: 80
