apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orcappdbmmono-ingress
  namespace: orcappdbmmono
  labels:
    app: orcappdbmmono
    app.kubernetes.io/name: orcappdbmmono
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
spec:
  rules:
    - host: orcappdbmmono.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orcappdbmmono-service
                port:
                  number: 80
